# Generated by Django 3.1 on 2020-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_dashboard_title', models.CharField(max_length=200)),
                ('user_dashboard_content', models.TextField()),
                ('user_dashboard_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
