# Generated by Django 3.1 on 2020-09-03 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200827_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='data uploaded')),
                ('video_length', models.TimeField(max_length=30)),
                ('video', models.FileField(upload_to='videos/footages/')),
            ],
        ),
        migrations.CreateModel(
            name='GraphCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
