# Generated by Django 3.1 on 2020-09-03 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_footage_graphcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date uploaded'),
        ),
    ]
