# Generated by Django 3.1 on 2020-09-10 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200903_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footage',
            name='video_length',
        ),
        migrations.AddField(
            model_name='footage',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='footage',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
