# Generated by Django 3.1 on 2020-09-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200910_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footage',
            name='author',
        ),
    ]
